logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    eu.wodrobina: INFO

multitenancy:
  dataSources:
    - tenantId: tenant1
      url: jdbc:h2:mem:tenant1
      username: any1
      password: anyPass1
      driverClassName: org.h2.Driver
    - tenantId: tenant2
      url: jdbc:h2:mem:tenant2
      username: any2
      password: anyPass2
      driverClassName: org.h2.Driver

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect